Algoritmo "20. EIMPAROUN "
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   :  Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
// ÍMPAR.
// Autor(a)    : Paulohpr
// Data atual  : 15/01/2025
Var
   n1, i: inteiro
Inicio
   Escreva ("Digite um número: ")
   Leia (n1)
   i <- n1 % 2
   Se (i = 1) Então
      Escreva ("O número:",i ,", é impar")
   FimSe
Fimalgoritmo