algoritmo "38.CONTAGEM6A11 "
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : 38) Escreva um programa que mostre na tela a seguinte contagem:
// 6 7 8 9 10 11 Acabou!
// Autor(a)    : Paulohpr
// Data atual  : 08/05/2025
var
   contador: inteiro
inicio
   contador <- 6
   Enquanto (contador <= 11) faca
      Escreva (contador)
      contador <- contador + 1
   fimEnquanto
   Escreva (" ACABOU!")
fimalgoritmo