algoritmo "39.CONTAGEM10A3 "
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   :  39) Faça um algoritmo que mostre na tela a seguinte contagem:
// 10 9 8 7 6 5 4 3 Acabou!
// Autor(a)    : Paulohpr
// Data atual  : 08/05/2025
var
   contador: inteiro
inicio
   contador <- 10
   Enquanto (contador >= 3) faca
      Escreva (contador)
      contador <- contador - 1
   fimEnquanto
   Escreva (" ACABOU!")
fimalgoritmo