algoritmo "40.CONTAGEM0A18 "
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : 40) Crie um aplicativo que mostre na tela a seguinte contagem:
// 0 3 6 9 12 15 18 Acabou!
// Autor(a)    : Paulohpr
// Data atual  : 08/05/2025
var
   contador: inteiro
inicio
   contador <- 0
   Enquanto (contador <= 18) faca
      Escreva (contador)
      contador <- contador + 3
   fimEnquanto
   Escreva (" ACABOU!")
fimalgoritmo