algoritmo "61. CONTADOR0A30DE3EM3"
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Crie um programa que mostre na tela a seguinte contagem,
// usando a estrutura“faça enquanto” 0 3 6 9 12 15 18 21 24 27 30 Acabou
// Autor(a)    : Paulohpr
// Data atual  : 17/05/2025
var
   cont: inteiro
inicio
   cont <- 0
   Repita
      Escreva (cont:3)
      cont <- cont + 3
   ate (cont = 33)
   Escreva (" Acabou")
fimalgoritmo