algoritmo "65. CONTADORDECRESCENTEPARA "
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : 65) Desenvolva um programa usando a estrutura “para”
// que mostre na tela a seguinte contagem:
// 100 90 80 70 60 50 40 30 20 10 0 Acabou!
// Autor(a)    : Paulohpr
// Data atual  : 17/05/2025
var
   c: inteiro
inicio
   Para c <- 100 ate 0 passo -10 faca
      Escreva (c)
   Fimpara
   Escreva (" Acabou!")
fimalgoritmo