algoritmo "SomaDeNumerosInteiros"
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   : Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório
// entre eles.
// Data atual  : 06/01/2025
var
   v1, v2, s: inteiro
inicio
   Escreva ("Digite um valor: ")
   Leia (v1)
   Escreva ("Digite outro valor: ")
   Leia (v2)
   s <- v1 + v2
   Escreva ("A soma entre", v1, " e", v2, " é igual a: ", s)
fimalgoritmo