algoritmo "64. CONTADORCOMPARA"
// Disciplina   : Algoritmo
// Professor   : Gustavo Guanabara
// Descrição   :  64) Desenvolva um programa usando a estrutura “para” que mostre na tela a
// seguinte contagem: 0 5 10 15 20 25 30 35 40 Acabou!
// Autor(a)    : Paulohpr
// Data atual  : 17/05/2025
var
   c: inteiro
inicio
   para c <- 0 ate 40 passo 5 faca
      Escreva (c)
   fimpara
   Escreva (" Acabou!")
fimalgoritmo